### ISSUE TITLE
Static functions seems to keep state?

### ISSUE THREAD

**Issue by hostep** [voku/urlify#11]
Hi!

Not using this library at the moment, was just playing around with it to see what it was capable of, and I found this weird problem.

See this code example:
```php
<?php

require_once('vendor/autoload.php');

use voku\helper\URLify;

echo 'de: ' . URLify::slug('coördineren ideeën reünie naïef', 'de', '-', true) . "\n";
echo 'nl: ' . URLify::slug('coördineren ideeën reünie naïef', 'nl', '-', true) . "\n";
```

Executing this gives the incorrect result for NL:
```
de: cooerdineren-ideeen-reuenie-naief
nl: cooerdineren-ideeen-reuenie-naief
```

But if we switch the two lines around:
```php
<?php

require_once('vendor/autoload.php');

use voku\helper\URLify;

echo 'nl: ' . URLify::slug('coördineren ideeën reünie naïef', 'nl', '-', true) . "\n";
echo 'de: ' . URLify::slug('coördineren ideeën reünie naïef', 'de', '-', true) . "\n";
```

The output is suddenly correct:
```
nl: coordineren-ideeen-reunie-naief
de: cooerdineren-ideeen-reuenie-naief
```

I have the feeling some state is being set and not resetted properly in between calls?

**Comment by hostep** [comment]
Sorry, just noticed you aren't supporting `nl` as a language.
But still, this feels strange that the output is different depending on what code you run first?

**Comment by voku** [comment]
```
use voku\helper\URLify;

echo 'de: ' . URLify::slug('coördineren ideeën reünie naïef', 'de', '-', true) . "\n";
echo 'nl: ' . URLify::slug('coördineren ideeën reünie naïef', 'nl', '-', true) . "\n";

echo 'nl: ' . URLify::slug('coördineren ideeën reünie naïef', 'nl', '-', true) . "\n";
echo 'de: ' . URLify::slug('coördineren ideeën reünie naïef', 'de', '-', true) . "\n";
```
de: cooerdineren-ideeen-reuenie-naief
nl: coordineren-ideeen-reunie-naief
nl: coordineren-ideeen-reunie-naief
de: cooerdineren-ideeen-reuenie-naief


PS: Support for "nl" and many other languages was added in the meantime, so I think it's fixed. :)
